// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfLgiwhQ66L8P32jY0VADw0cNWmcfUIg',
    appId: '1:826115118753:web:97e82a487b3e7b7c0f82e0',
    messagingSenderId: '826115118753',
    projectId: 'mma-project-91699',
    authDomain: 'mma-project-91699.firebaseapp.com',
    databaseURL: 'https://mma-project-91699-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mma-project-91699.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_thm8Ev5kHeYcBmYPvbF5hX4XxPDaFsc',
    appId: '1:826115118753:android:769a7b4832583a2e0f82e0',
    messagingSenderId: '826115118753',
    projectId: 'mma-project-91699',
    databaseURL: 'https://mma-project-91699-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mma-project-91699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxEunTCTXSDe1gY080Pc7JjYq5uAzURmc',
    appId: '1:826115118753:ios:bc79284bafe6aec30f82e0',
    messagingSenderId: '826115118753',
    projectId: 'mma-project-91699',
    databaseURL: 'https://mma-project-91699-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mma-project-91699.firebasestorage.app',
    iosBundleId: 'com.example.stopwatchLeaderboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxEunTCTXSDe1gY080Pc7JjYq5uAzURmc',
    appId: '1:826115118753:ios:bc79284bafe6aec30f82e0',
    messagingSenderId: '826115118753',
    projectId: 'mma-project-91699',
    databaseURL: 'https://mma-project-91699-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mma-project-91699.firebasestorage.app',
    iosBundleId: 'com.example.stopwatchLeaderboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPfLgiwhQ66L8P32jY0VADw0cNWmcfUIg',
    appId: '1:826115118753:web:02a5588f94912b910f82e0',
    messagingSenderId: '826115118753',
    projectId: 'mma-project-91699',
    authDomain: 'mma-project-91699.firebaseapp.com',
    databaseURL: 'https://mma-project-91699-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mma-project-91699.firebasestorage.app',
  );

}