name: stopwatch_leaderboard_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^9.0.0
  firebase_core:
  cloud_firestore:
  firebase_messaging: ^16.1.2  
  shared_preferences: ^2.2.2
  provider:
  flutter_local_notifications: ^21.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # <-- Add this line

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png" # <-- Make sure this matches your file path!
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#0175C2" # You can change this to match your app's brand color
    theme_color: "#0175C2"